[package]
name = "tmpl-ructe"
version = "0.1.0"
edition = "2021"
publish = false
license = "Apache-2.0"

[dependencies]
tmpls = { version = "*", path = ".." }

ructe = "0.17.2"

[build-dependencies]
ructe = "0.17.2"
