[package]
name = "tmpl-markup"
version = "0.1.0"
edition = "2021"
publish = false
license = "Apache-2.0"

[dependencies]
tmpls = { version = "*", path = ".." }

markup = { version = "0.15", features = ["itoa"] }
